### ISSUE TITLE
Instant crash when using correct tool on correct block types

### ISSUE THREAD

**Issue by AlexanderwithaA** [JongWasTaken/moretools#1]
The game just instantly crashes when using any of the tools on their intended blocks.
I'm running fabric api 0.96.11+1.20.4, moretools 1.1.0, and polymer 0.7.6+1.20.4

https://github.com/JongWasTaken/moretools/assets/101488091/e717ce9b-946f-458c-a0c6-aa609a4bc6f7

https://github.com/JongWasTaken/moretools/assets/101488091/3e4ad61a-2793-4eb7-ab14-1bffc1cdf00d

```
Time: 2024-03-23 14:31:12
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_2248.method_9576(net.minecraft.class_1937, net.minecraft.class_2338, net.minecraft.class_2680, net.minecraft.class_1657)'
	at pw.smto.ExcavatorToolItem.breakBlocks(ExcavatorToolItem.java:70)
	at net.minecraft.class_3225.handler$zmk000$moretools$tryBreakBlock(class_3225.java:1025)
	at net.minecraft.class_3225.method_14266(class_3225.java:267)
	at net.minecraft.class_3225.method_21717(class_3225.java:228)
	at net.minecraft.class_3225.method_14263(class_3225.java:159)
	at net.minecraft.class_3244.method_12066(class_3244.java:1077)
	at net.minecraft.class_2846.method_12361(class_2846.java:42)
	at net.minecraft.class_2846.method_11054(class_2846.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by JongWasTaken** [comment]
Hello, and thank you for creating an issue.

I just tried replicating this and had mixed results.
In the development version of minecraft i didn't encounter any issues, while a fresh install on 1.20.4 wouldn't even start up for me.
I made this mod for a private server on 1.20.1, so i didn't really test higher versions.

Now, i did a quick recompile with newer fabric and polymer versions and all seems to work fine now, so it was probably an issue with one of those.

[I just uploaded a new version specifically targeting 1.20.4 to Modrinth.](https://modrinth.com/mod/more-tools/version/Wr8xdOs9)
Please tell me if it fixes the issue.
